services:
  - name: fastapi-api
    type: web
    plan: free
    region: frankfurt  # Или другой регион: mumbai, ohio, oregon
    repo: https://github.com/Stan26-2020/UpscalerMagicBot/tree/main
    branch: main
    runtime: python
    python version: 3.9.13
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn api.api:app --host 0.0.0.0 --port $PORT --workers 2
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: API_KEY
        sync: false  # Устанавливается вручную в панели Render
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ENVIRONMENT
        value: "production"
    healthCheckPath: /health
    healthCheckTimeout: 120

  - name: telegram-bot
    type: worker  # Лучше подходит для long-running процессов
    plan: free
    region: frankfurt  # Должен совпадать с регионом API
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    branch: main
    runtime: python
    python version: 3.9.13
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m bot.bot
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: API_ENDPOINT
        value: https://fastapi-api.onrender.com
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: ENVIRONMENT

        value: "production"

services:
  - name: upscaler-bot
    python:
      version: 3.9.13
    buildCommand: |
      python -m pip install --upgrade pip
      pip install wheel setuptools
      pip install -r requirements.txt
    systemDependencies:
      - libgl1
      - libglib2.0-0
      - libsm6
      - libxext6
      - libxrender1
      
services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    pythonVersion: "3.11.8"
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
